// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfVlKhd0bQ0YAt5MRrynYLPcex-jcNi2I',
    appId: '1:226802698678:android:14d295ba62117a78399917',
    messagingSenderId: '226802698678',
    projectId: 'waffaq-x',
    storageBucket: 'waffaq-x.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiOaOe3KLfHUIcXmmh4xs4pY4j9ITTaY8',
    appId: '1:226802698678:ios:f8558b7f06f98f6e399917',
    messagingSenderId: '226802698678',
    projectId: 'waffaq-x',
    storageBucket: 'waffaq-x.appspot.com',
    androidClientId: '226802698678-q1v7310edhnoi9u3hcgedpi08it7gc3c.apps.googleusercontent.com',
    iosClientId: '226802698678-6cdstolatrr668htdmuqpjk4cuovvh2k.apps.googleusercontent.com',
    iosBundleId: 'com.example.waffaqx',
  );
}
